### ISSUE TITLE
Use a keyword options on `pipe`.

### ISSUE THREAD

**Issue by vic** [antonmi/flowex#1]
Hello @antonmi,

First of all, thank you very much for creating flowex, looks amazingly useful. 

I overall like your API design, just one tiny thing I think could be improved. When defining the number of worker processes a particular component can have

```elixir
  pipe :mult_by_two, 3
```

how about using a more idiomatic keyed option instead of just giving the number

```elixir
  pipe :mult_by_two, workers: 3
```

The options advantage is we are being more explicit about what `3` means (at the cost of writing a bit more, but I believe many Elixir libraries prefer to be explicit about intent)

I could provide a PR if you are interested in this change. 

Cheers, and thanks again for Flowex :)

**Comment by antonmi** [comment]
Hi, @vic.
Thanks for the comment.
Number of processes is the only options one can send to pipe macro, so (for now) I think keyword is not necessary.

**Comment by Kukunin** [comment]
But what's about future?

If you'll add one more option, will you break API or maintain support of both ways.

**Comment by antonmi** [comment]
I wouldn't consider the number of parallel processes as a simple option. It is an essential argument. So I don't want keyword syntax for it. When we have options for pipe macro, the interface will be like:
```elixir
pipe :mult_by_two, 3, opt1: 5, opt2: 42
# or with 1 as default number
pipe :mult_by_two, opt1: 5, opt2: 42
```

**Comment by lain1936** [comment]
`pipe :add_one, 
        name: fn ->String.to_atom("Flowex_ModuleName_PrevToNextLayerOrIndexNumber_add_one") end`
`pipe :mult_by_two, 
        name: fn ->String.to_atom("Flowex_ModuleName_LayerOrIndexNumber_mult_by_two") end,
        min_time:30,  
        step_by: 2, 
        max_number:10
        `

How about adding options to measure the execution time of task  (timestamp, etc. in microseconds), then subscribe to a specified name (some unique strategy key ) ,So we can increase the numbers of process dynamically ?
(er, It seems to about situation of interval timer outside of the pipeline)

**Comment by antonmi** [comment]
Hi, @lain1936 !
Thanks for interesting in Flowex!
It's a good idea.
Please make a separate issue and describe the feature there.
Thanks!

**Comment by antonmi** [comment]
Hi, guys! Thanks for the discussion.
I will introduce options that can be passed to a component via `opts` keyword.
And you convinced me to make count as a keyword.

So, from now, (starting from 0.5.0 version, I'll release soon) pipe definition will look like:
```elixir
pipe :my_pipe, opts: %{a: 1, b:2}, count: 10
```
