### ISSUE TITLE
Pipeline supervisor doesn't create full flows when it is killed.

### ISSUE THREAD

**Issue by blueringlab** [antonmi/flowex#11]
I have a pipeline as following.

```
defmodule Helios.Pipeline.Delete do
use Flowex.Pipeline

pipe Helios.Flow.DeleteAsset, count: 1
pipe Helios.Flow.Finalize, count: 1
end
```
And I connect the pipeline to superviser (strategy: :one_for_one).

`pipeline_delete = Helios.Pipeline.Delete.supervised_start(supervisor_pid)`

After the application is started and the pipeline is up andruning, I killed the pipeline process, but I can see only Producer process is back, but not the others.

**Comment by antonmi** [comment]
Thanks @blueringlab !
Will fix soon!

**Comment by antonmi** [comment]
Hi, @blueringlab !
I've changed starting strategy for pipeline.
Please, try new 0.5.2 version of the library.
