### ISSUE TITLE
Flowex.Client.call() doesn't execute pipe line concurrently.

### ISSUE THREAD

**Issue by blueringlab** [antonmi/flowex#14]
I am using Flowex 0.5.2.
I have a application uses Flowex.Client.call() but it doesn't execute the pipeline concurrently.

Flowex.Client.call() is called from separated processes which is created by Task.async.
I want to use Flowex.Client.call() function to receive final value. 

`Enum.each(requests, &( Task.async(__MODULE__, :do_task, [self(), client_pid, &1]) ))`

And do_task() function calls Flowex.Client.call().

>def do_task(owner, client_pid, request) do
>   result = Flowex.Client.call(pipeline_pid, request) do
>
>    send( owner, {:completed, result})
>  end

When I do this way, I found pipeline process only one data at a time.
Once I change the call to cast() it processes concurrently. With case() I cannot get the result of the pipeline without extra message sending.

Thank you.

**Comment by blueringlab** [comment]
I understand wrong. I should have created FlowEx.Client for each request. 
I close this issue.

**Comment by antonmi** [comment]
Hi, @blueringlab !
Thanks for using Flowex!
Yes, you should create a client for each request or ... you even needn't clients at all.
You can call pipeline directly in a Task.
