### ISSUE TITLE
Triggering the error pipeline

### ISSUE THREAD

**Issue by tchoutri** [antonmi/flowex#15]
Hi! I am using Flowex to organise my code, and noticed that my functions should return the `%__MODULE__{}` struct when the function succeeds.  
However, how can I trigger the error pipe when a `case do` in my function fails?
Or maybe I didn't understand how flowex handles that.

Have a nice day!

**Comment by antonmi** [comment]
Hi, @tchoutri !
You can just raise a custom exception in the pipe and catch in error_pipe.

Thank for using Flowex!

**Comment by tchoutri** [comment]
Okay cool, because I was initially using a return tuple (in the like of an `Either` monad). Perhaps a full working example would be **as useful** as your example starting strategies (which were super helpful, thanks again for that!)
