### ISSUE TITLE
Is flowex not maintained anymore ?

### ISSUE THREAD

**Issue by scorsi** [antonmi/flowex#19]
Hello,

I would like to use that lib into my project but by seeing that there's not any updates since 2 years at least, I'm asking my-self if it is still a viable project for production-usage. Does this project just dead ?

I think I should go for [flow](https://github.com/dashbitco/flow) which is quite different but we can achieve quite the same thing.

Thanks,

**Comment by antonmi** [comment]
Hey @scorsi !
Sorry for the late response.
Unfortunately the project is not in development right now.
But I think it still works well.
I'm going to review it a bit soon in order to be sure it works with latest Elixir version

**Comment by antonmi** [comment]
About your comparison with Flow.
They are quite different. Flow is only for computation on collections. While Flowex is more general framework that allows you to create pipelines with arbitrary functionality.

**Comment by scorsi** [comment]
Thanks for your answer (and sorry for the delay).

I did use flowex and it's actually working for what I need to.
